version: '3'

services:
  elasticsearch:
    image: elasticsearch:2.4
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    mem_limit: 2g
    networks:
      - main

  web:
    build: .
    devices:
      - /dev/snd
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    image: serenity_proj
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./serenity:/home/projects/serenity
    ports:
      - "8000:8000"
    env_file: config.env
    networks:
      - main
    depends_on:
      - elasticsearch

networks:
  main:
    driver: bridge