# Generated by Django 4.2.15 on 2024-08-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='book_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
