# Generated by Django 4.2.15 on 2024-08-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_summary_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='book_title',
        ),
    ]
