# Generated by Django 4.2.15 on 2024-08-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_summary_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='book',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_summary', to='books.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_summary', to='books.summary'),
        ),
    ]
