# Generated by Django 5.1 on 2024-08-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_savebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveBook',
        ),
    ]
